Received: from vade-backend13.dreamhost.com (caibbdcaaaai.dreamhost.com [208.113.200.8])
	(using TLSv1.2 with cipher AECDH-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by homiemail-mx28.g.dreamhost.com (Postfix) with ESMTPS id 12BCB20049033
	for <valencio@rsoft.net>; Wed,  5 Sep 2018 18:11:27 -0700 (PDT)
Received: from mail3.mercurygate.net (mail4.mercurygate.net [199.115.76.26])
	by vade-backend13.dreamhost.com (Postfix) with ESMTP id 6B9A040001047
	for <valencio@rsoft.net>; Wed,  5 Sep 2018 18:11:26 -0700 (PDT)
Received: from ti1pa.mercurygate.net ([10.115.76.97]) by mercurygate.net with MailEnable ESMTP; Wed, 5 Sep 2018 21:11:17 -0400
Reply-To: <URload@t-insight.com>
From: <URload@t-insight.com>
To: <valencio@rsoft.net>
Subject: Request for Bids
Date: Wed, 5 Sep 2018 18:11:17 -0700
Message-ID: <896600302.619163.1536196283862.JavaMail.mgadmin@TI1PA>
MIME-Version: 1.0
Content-Type: multipart/alternative;
	boundary="----=_NextPart_000_01D3_01D44553.285F8DE0"
X-Mailer: Microsoft Outlook 16.0
Thread-Index: AQLsGxv73OqxcFwl0PvqXjfGfK/9dw==

This is a multipart message in MIME format.

------=_NextPart_000_01D3_01D44553.285F8DE0
Content-Type: text/plain;
	charset="utf-8"
Content-Transfer-Encoding: quoted-printable

You have been designated as one of the preferred carriers to bid on a =
load for UNITED RENTALS INC..=20

Please reply by 09/06/2018 09:00 AM Eastern Time=20

Please click here =
<https://t-insight.mercurygate.net/MercuryGate/login/mgLogin.jsp>  to =
submit your bid. We will award the bid on price and service and we will =
notify the winner via email.=20

Bid Request: 	=09
Load: 	42252832L=09
Max Bid Amount: 	$ 9.9999999E7=09
Bid Decrement: 	$ 0.0=09
Book-It-Now Price: 	$ =09

Plan:

1	 Pickup	 UNITED RENTALS,  UNITED RENTALS,  19919 WOODINVILLE SNOHOMISH =
RD,  NE,  WOODINVILLE, WA. 98072=20

UNITED RENTALS,=20
Qty: 0.0 Weight: 5,000 lb=20
Schedule:
09/06/2018 08:00 AM
09/06/2018 05:00 PM =09
2	 Drop	 SILVER CREEK CONTRACTING,  SILVER CREEK CONTRACTING,  MISSION =
HWY & TIMINE RD,  MISSION, OR. 97801=20

SILVER CREEK CONTRACTING,=20
Qty: 0.0 Weight: 5,000 lb=20
Schedule:
09/06/2018 08:00 AM
09/06/2018 05:00 PM =09

=20

Pallets:	0.0 =09
Equipment:	=09
Services:=09
Special Instructions:	QUOTE IS VALID FOR 20 DAYS.CREATED BY CRUBIO =
MUSTTT DELIVER BY 09/06/2018 1700 !* FLATBED * PPE REQUIRED. =09

We appreciate you taking the time to participate in our bid process.=20


------=_NextPart_000_01D3_01D44553.285F8DE0
Content-Type: text/html;
	boundary="----=_Part_619162_190805445.1536196283862";
	charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<META HTTP-EQUIV=3D"Content-Type" CONTENT=3D"text/html; =
charset=3Dutf-8">

<title>Bid Request</title>
<style>
	table {
		width: 100%; 	=09
	}
	th { vertical-align: top; text-align: right; }
	td { padding-left: 20px; font-family: sans-serif; font-size: smaller; }
	p.address { margin: 0; }
	.boxed {
		border: solid black 1px;
		margin: 0 0 0 0;
		padding: 10px 4px 4px 4px;
		vertical-align: text-top;
	}
</style>
</head>
<body>
<p>
	You have been designated as one of the preferred carriers to bid on a =
load for
	UNITED RENTALS INC..
</p>
<p>
	Please reply by 09/06/2018 09:00 AM Eastern Time
</p>

<p>
		Please <a =
href=3D"https://t-insight.mercurygate.net/MercuryGate/login/mgLogin.jsp">=
click here</a> to submit your bid.
		We will award the bid on price and service and we will notify the =
winner via email.
</p>

<table>
	<tr><td width=3D"10%" style=3D"text-align: right;"><strong>Bid Request: =
</strong></td><td width=3D"60%" style=3D"text-align: left;"></td></tr>
	<tr><td width=3D"10%" style=3D"text-align: right;"><strong>Load: =
</strong></td><td width=3D"60%" style=3D"text-align: =
left;">42252832L</td></tr>
	<tr><td width=3D"10%" style=3D"text-align: right;"><strong>Max Bid =
Amount: </strong></td><td width=3D"60%" style=3D"text-align: left;">$ =
9.9999999E7</td></tr>
	<tr><td width=3D"10%" style=3D"text-align: right;"><strong>Bid =
Decrement: </td><td width=3D"60%" style=3D"text-align: left;">$ =
0.0</td></tr>
	<tr><td width=3D"10%" style=3D"text-align: right;"><strong>Book-It-Now =
Price: </strong></td><td width=3D"60%" style=3D"text-align: left;">$ =
</td></tr>
</table>
<h3 style=3D"margin-left:10px;">Plan:</h3>

<table width=3D"80%" border=3D"none" cellpadding=3D"10px" =
style=3D"border-collapse:collapse;" cols=3D"5% 10% 30% 30% 20%">
	<tr>
		<td class=3D"boxed" style=3D"text-align: center;">1</td>
		<td class=3D"boxed" style=3D"text-align: center;">Pickup</td>
		<td class=3D"boxed">
			<strong>
			UNITED RENTALS,&nbsp;
							UNITED RENTALS,&nbsp;
				19919 WOODINVILLE SNOHOMISH RD,&nbsp;
									NE,&nbsp;
										WOODINVILLE, WA. 98072
			</strong>
			<div><strong>UNITED RENTALS, </strong></div>
			<div>
				<span style=3D"width:40%"><strong>Qty:</strong>&nbsp;0.0</span>
				<span =
style=3D"width:60%;text-align:left;"><strong>Weight:</strong>&nbsp;5,000 =
lb</span>
			</div>
		</td>
		<td class=3D"boxed">
			<strong>Schedule:</strong><br/>
			09/06/2018 08:00 AM<br>
			09/06/2018 05:00 PM
		</td>
	</tr>
		<tr>
		<td class=3D"boxed" style=3D"text-align: center;">2</td>
		<td class=3D"boxed" style=3D"text-align: center;">Drop</td>
		<td class=3D"boxed">
			<strong>
			SILVER CREEK CONTRACTING,&nbsp;
							SILVER CREEK CONTRACTING,&nbsp;
				MISSION HWY &amp; TIMINE RD,&nbsp;
										MISSION, OR. 97801
			</strong>
			<div><strong>SILVER CREEK CONTRACTING, </strong></div>
			<div>
				<span style=3D"width:40%"><strong>Qty:</strong>&nbsp;0.0</span>
				<span =
style=3D"width:60%;text-align:left;"><strong>Weight:</strong>&nbsp;5,000 =
lb</span>
			</div>
		</td>
		<td class=3D"boxed">
			<strong>Schedule:</strong><br/>
			09/06/2018 08:00 AM<br>
			09/06/2018 05:00 PM
		</td>
	</tr>
	</table>
<p>&nbsp;</p>
<table>
	<tr><td><strong>Pallets:</strong></td><td>
		0.0
		</td></tr>
	</tr>
	<tr><td><strong>Equipment:</strong></td><td>
       			</td></tr>
	<tr><td><strong>Services:</strong></td><td>
       	   	<tr><td><strong>Special Instructions:</strong></td><td>
		QUOTE IS VALID FOR 20 DAYS.CREATED BY CRUBIO
MUSTTT DELIVER BY 09/06/2018 1700 !* FLATBED *

PPE REQUIRED.
		</td></tr>
	</tr>
</table>
<p>
	We appreciate you taking the time to participate in our bid process.
</p>

</body>
</html>
------=_NextPart_000_01D3_01D44553.285F8DE0--
