//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruckStopService.TruckStopServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TruckStopService.TruckStopServiceReference.LoadDeleteRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TruckStopService.TruckStopServiceReference.LoadListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TruckStopService.TruckStopServiceReference.LoadDeleteByLoadNumberRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TruckStopService.TruckStopServiceReference.LoadViewsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TruckStopService.TruckStopServiceReference.LoadViewsByLoadNumberRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TruckStopService.TruckStopServiceReference.LoadPostingRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IntegrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IntegrationId {
            get {
                return this.IntegrationIdField;
            }
            set {
                if ((this.IntegrationIdField.Equals(value) != true)) {
                    this.IntegrationIdField = value;
                    this.RaisePropertyChanged("IntegrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadDeleteRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    [System.SerializableAttribute()]
    public partial class LoadDeleteRequest : TruckStopService.TruckStopServiceReference.RequestBase {
        
        private int[] LoadsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int[] Loads {
            get {
                return this.LoadsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadsField, value) != true)) {
                    this.LoadsField = value;
                    this.RaisePropertyChanged("Loads");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadListRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    [System.SerializableAttribute()]
    public partial class LoadListRequest : TruckStopService.TruckStopServiceReference.RequestBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadDeleteByLoadNumberRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    [System.SerializableAttribute()]
    public partial class LoadDeleteByLoadNumberRequest : TruckStopService.TruckStopServiceReference.RequestBase {
        
        private string[] LoadNumbersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] LoadNumbers {
            get {
                return this.LoadNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadNumbersField, value) != true)) {
                    this.LoadNumbersField = value;
                    this.RaisePropertyChanged("LoadNumbers");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadViewsRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    [System.SerializableAttribute()]
    public partial class LoadViewsRequest : TruckStopService.TruckStopServiceReference.RequestBase {
        
        private int LoadField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Load {
            get {
                return this.LoadField;
            }
            set {
                if ((this.LoadField.Equals(value) != true)) {
                    this.LoadField = value;
                    this.RaisePropertyChanged("Load");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadViewsByLoadNumberRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    [System.SerializableAttribute()]
    public partial class LoadViewsByLoadNumberRequest : TruckStopService.TruckStopServiceReference.RequestBase {
        
        private string LoadNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LoadNumber {
            get {
                return this.LoadNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadNumberField, value) != true)) {
                    this.LoadNumberField = value;
                    this.RaisePropertyChanged("LoadNumber");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadPostingRequest", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Posting")]
    [System.SerializableAttribute()]
    public partial class LoadPostingRequest : TruckStopService.TruckStopServiceReference.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FullImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HandleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TruckStopService.TruckStopServiceReference.Load[] LoadsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FullImport {
            get {
                return this.FullImportField;
            }
            set {
                if ((this.FullImportField.Equals(value) != true)) {
                    this.FullImportField = value;
                    this.RaisePropertyChanged("FullImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((object.ReferenceEquals(this.HandleField, value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TruckStopService.TruckStopServiceReference.Load[] Loads {
            get {
                return this.LoadsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadsField, value) != true)) {
                    this.LoadsField = value;
                    this.RaisePropertyChanged("Loads");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Load", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class Load : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AffiliateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditField;
        
        private System.DateTime DeliveryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EquipmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TruckStopService.TruckStopServiceReference.TrailerOptionType[] EquipmentOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuelPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDailyField;
        
        private bool IsFavoriteField;
        
        private bool IsLoadFullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LengthField;
        
        private int LoadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoadNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MileageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentAmountField;
        
        private System.DateTime PickUpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickUpTimeField;
        
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StopsField;
        
        private string TypeOfEquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WeightField;
        
        private int WidthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Affiliate {
            get {
                return this.AffiliateField;
            }
            set {
                if ((object.ReferenceEquals(this.AffiliateField, value) != true)) {
                    this.AffiliateField = value;
                    this.RaisePropertyChanged("Affiliate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditField, value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DeliveryDate {
            get {
                return this.DeliveryDateField;
            }
            set {
                if ((this.DeliveryDateField.Equals(value) != true)) {
                    this.DeliveryDateField = value;
                    this.RaisePropertyChanged("DeliveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryTime {
            get {
                return this.DeliveryTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryTimeField, value) != true)) {
                    this.DeliveryTimeField = value;
                    this.RaisePropertyChanged("DeliveryTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCity {
            get {
                return this.DestinationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCityField, value) != true)) {
                    this.DestinationCityField = value;
                    this.RaisePropertyChanged("DestinationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCountry {
            get {
                return this.DestinationCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCountryField, value) != true)) {
                    this.DestinationCountryField = value;
                    this.RaisePropertyChanged("DestinationCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationState {
            get {
                return this.DestinationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationStateField, value) != true)) {
                    this.DestinationStateField = value;
                    this.RaisePropertyChanged("DestinationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((object.ReferenceEquals(this.DistanceField, value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EquipmentID {
            get {
                return this.EquipmentIDField;
            }
            set {
                if ((this.EquipmentIDField.Equals(value) != true)) {
                    this.EquipmentIDField = value;
                    this.RaisePropertyChanged("EquipmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TruckStopService.TruckStopServiceReference.TrailerOptionType[] EquipmentOptions {
            get {
                return this.EquipmentOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentOptionsField, value) != true)) {
                    this.EquipmentOptionsField = value;
                    this.RaisePropertyChanged("EquipmentOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelPrice {
            get {
                return this.FuelPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.FuelPriceField, value) != true)) {
                    this.FuelPriceField = value;
                    this.RaisePropertyChanged("FuelPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDaily {
            get {
                return this.IsDailyField;
            }
            set {
                if ((this.IsDailyField.Equals(value) != true)) {
                    this.IsDailyField = value;
                    this.RaisePropertyChanged("IsDaily");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsFavorite {
            get {
                return this.IsFavoriteField;
            }
            set {
                if ((this.IsFavoriteField.Equals(value) != true)) {
                    this.IsFavoriteField = value;
                    this.RaisePropertyChanged("IsFavorite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsLoadFull {
            get {
                return this.IsLoadFullField;
            }
            set {
                if ((this.IsLoadFullField.Equals(value) != true)) {
                    this.IsLoadFullField = value;
                    this.RaisePropertyChanged("IsLoadFull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Length {
            get {
                return this.LengthField;
            }
            set {
                if ((object.ReferenceEquals(this.LengthField, value) != true)) {
                    this.LengthField = value;
                    this.RaisePropertyChanged("Length");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LoadId {
            get {
                return this.LoadIdField;
            }
            set {
                if ((this.LoadIdField.Equals(value) != true)) {
                    this.LoadIdField = value;
                    this.RaisePropertyChanged("LoadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoadNumber {
            get {
                return this.LoadNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadNumberField, value) != true)) {
                    this.LoadNumberField = value;
                    this.RaisePropertyChanged("LoadNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mileage {
            get {
                return this.MileageField;
            }
            set {
                if ((object.ReferenceEquals(this.MileageField, value) != true)) {
                    this.MileageField = value;
                    this.RaisePropertyChanged("Mileage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCity {
            get {
                return this.OriginCityField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCityField, value) != true)) {
                    this.OriginCityField = value;
                    this.RaisePropertyChanged("OriginCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCountry {
            get {
                return this.OriginCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCountryField, value) != true)) {
                    this.OriginCountryField = value;
                    this.RaisePropertyChanged("OriginCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginState {
            get {
                return this.OriginStateField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginStateField, value) != true)) {
                    this.OriginStateField = value;
                    this.RaisePropertyChanged("OriginState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentAmountField, value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime PickUpDate {
            get {
                return this.PickUpDateField;
            }
            set {
                if ((this.PickUpDateField.Equals(value) != true)) {
                    this.PickUpDateField = value;
                    this.RaisePropertyChanged("PickUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickUpTime {
            get {
                return this.PickUpTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PickUpTimeField, value) != true)) {
                    this.PickUpTimeField = value;
                    this.RaisePropertyChanged("PickUpTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecInfo {
            get {
                return this.SpecInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecInfoField, value) != true)) {
                    this.SpecInfoField = value;
                    this.RaisePropertyChanged("SpecInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stops {
            get {
                return this.StopsField;
            }
            set {
                if ((object.ReferenceEquals(this.StopsField, value) != true)) {
                    this.StopsField = value;
                    this.RaisePropertyChanged("Stops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TypeOfEquipment {
            get {
                return this.TypeOfEquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeOfEquipmentField, value) != true)) {
                    this.TypeOfEquipmentField = value;
                    this.RaisePropertyChanged("TypeOfEquipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((object.ReferenceEquals(this.WeightField, value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrailerOptionType", Namespace="http://schemas.datacontract.org/2004/07/Truckstop2.Objects")]
    public enum TrailerOptionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tarps = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hazardous = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PalletExchange = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Team = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expedited = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnBase", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TruckStopService.TruckStopServiceReference.LoadPostingListReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TruckStopService.TruckStopServiceReference.LoadViewsReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TruckStopService.TruckStopServiceReference.LoadPostingReturn))]
    public partial class ReturnBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TruckStopService.TruckStopServiceReference.Error[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TruckStopService.TruckStopServiceReference.Error[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadPostingListReturn", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class LoadPostingListReturn : TruckStopService.TruckStopServiceReference.ReturnBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TruckStopService.TruckStopServiceReference.PostResult[] LoadsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TruckStopService.TruckStopServiceReference.PostResult[] Loads {
            get {
                return this.LoadsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadsField, value) != true)) {
                    this.LoadsField = value;
                    this.RaisePropertyChanged("Loads");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadViewsReturn", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class LoadViewsReturn : TruckStopService.TruckStopServiceReference.ReturnBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TruckStopService.TruckStopServiceReference.LoadView[] LoadViewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TruckStopService.TruckStopServiceReference.LoadView[] LoadViews {
            get {
                return this.LoadViewsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadViewsField, value) != true)) {
                    this.LoadViewsField = value;
                    this.RaisePropertyChanged("LoadViews");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadPostingReturn", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class LoadPostingReturn : TruckStopService.TruckStopServiceReference.ReturnBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] LoadNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] LoadsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] LoadNumbers {
            get {
                return this.LoadNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadNumbersField, value) != true)) {
                    this.LoadNumbersField = value;
                    this.RaisePropertyChanged("LoadNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Loads {
            get {
                return this.LoadsField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadsField, value) != true)) {
                    this.LoadsField = value;
                    this.RaisePropertyChanged("Loads");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/WebServices")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SuggestionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Suggestions {
            get {
                return this.SuggestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SuggestionsField, value) != true)) {
                    this.SuggestionsField = value;
                    this.RaisePropertyChanged("Suggestions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostResult", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class PostResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TruckStopService.TruckStopServiceReference.TrailerOptionType[] EquipmentOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TruckStopService.TruckStopServiceReference.EquipmentTypes EquipmentTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HandleNameField;
        
        private int IdField;
        
        private bool IsFullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoadNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoadViewCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickupDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCity {
            get {
                return this.DestinationCityField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCityField, value) != true)) {
                    this.DestinationCityField = value;
                    this.RaisePropertyChanged("DestinationCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationCountry {
            get {
                return this.DestinationCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationCountryField, value) != true)) {
                    this.DestinationCountryField = value;
                    this.RaisePropertyChanged("DestinationCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationState {
            get {
                return this.DestinationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationStateField, value) != true)) {
                    this.DestinationStateField = value;
                    this.RaisePropertyChanged("DestinationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipment {
            get {
                return this.EquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentField, value) != true)) {
                    this.EquipmentField = value;
                    this.RaisePropertyChanged("Equipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TruckStopService.TruckStopServiceReference.TrailerOptionType[] EquipmentOptions {
            get {
                return this.EquipmentOptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentOptionsField, value) != true)) {
                    this.EquipmentOptionsField = value;
                    this.RaisePropertyChanged("EquipmentOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TruckStopService.TruckStopServiceReference.EquipmentTypes EquipmentTypes {
            get {
                return this.EquipmentTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipmentTypesField, value) != true)) {
                    this.EquipmentTypesField = value;
                    this.RaisePropertyChanged("EquipmentTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HandleName {
            get {
                return this.HandleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HandleNameField, value) != true)) {
                    this.HandleNameField = value;
                    this.RaisePropertyChanged("HandleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsFull {
            get {
                return this.IsFullField;
            }
            set {
                if ((this.IsFullField.Equals(value) != true)) {
                    this.IsFullField = value;
                    this.RaisePropertyChanged("IsFull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoadNumber {
            get {
                return this.LoadNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LoadNumberField, value) != true)) {
                    this.LoadNumberField = value;
                    this.RaisePropertyChanged("LoadNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoadViewCount {
            get {
                return this.LoadViewCountField;
            }
            set {
                if ((this.LoadViewCountField.Equals(value) != true)) {
                    this.LoadViewCountField = value;
                    this.RaisePropertyChanged("LoadViewCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCity {
            get {
                return this.OriginCityField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCityField, value) != true)) {
                    this.OriginCityField = value;
                    this.RaisePropertyChanged("OriginCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCountry {
            get {
                return this.OriginCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCountryField, value) != true)) {
                    this.OriginCountryField = value;
                    this.RaisePropertyChanged("OriginCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginState {
            get {
                return this.OriginStateField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginStateField, value) != true)) {
                    this.OriginStateField = value;
                    this.RaisePropertyChanged("OriginState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Payment {
            get {
                return this.PaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentField, value) != true)) {
                    this.PaymentField = value;
                    this.RaisePropertyChanged("Payment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickupDate {
            get {
                return this.PickupDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PickupDateField, value) != true)) {
                    this.PickupDateField = value;
                    this.RaisePropertyChanged("PickupDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquipmentTypes", Namespace="http://schemas.datacontract.org/2004/07/Truckstop2.Objects")]
    [System.SerializableAttribute()]
    public partial class EquipmentTypes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> FullLoadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCategorizableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsComboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTruckPostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MapToIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<TruckStopService.TruckStopServiceReference.TrailerOptionType> RequiredOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WebserviceOnlyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> FullLoad {
            get {
                return this.FullLoadField;
            }
            set {
                if ((this.FullLoadField.Equals(value) != true)) {
                    this.FullLoadField = value;
                    this.RaisePropertyChanged("FullLoad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCategorizable {
            get {
                return this.IsCategorizableField;
            }
            set {
                if ((this.IsCategorizableField.Equals(value) != true)) {
                    this.IsCategorizableField = value;
                    this.RaisePropertyChanged("IsCategorizable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCombo {
            get {
                return this.IsComboField;
            }
            set {
                if ((this.IsComboField.Equals(value) != true)) {
                    this.IsComboField = value;
                    this.RaisePropertyChanged("IsCombo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTruckPost {
            get {
                return this.IsTruckPostField;
            }
            set {
                if ((this.IsTruckPostField.Equals(value) != true)) {
                    this.IsTruckPostField = value;
                    this.RaisePropertyChanged("IsTruckPost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MapToId {
            get {
                return this.MapToIdField;
            }
            set {
                if ((this.MapToIdField.Equals(value) != true)) {
                    this.MapToIdField = value;
                    this.RaisePropertyChanged("MapToId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<TruckStopService.TruckStopServiceReference.TrailerOptionType> RequiredOption {
            get {
                return this.RequiredOptionField;
            }
            set {
                if ((this.RequiredOptionField.Equals(value) != true)) {
                    this.RequiredOptionField = value;
                    this.RaisePropertyChanged("RequiredOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WebserviceOnly {
            get {
                return this.WebserviceOnlyField;
            }
            set {
                if ((this.WebserviceOnlyField.Equals(value) != true)) {
                    this.WebserviceOnlyField = value;
                    this.RaisePropertyChanged("WebserviceOnly");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadView", Namespace="http://schemas.datacontract.org/2004/07/WebServices.Objects")]
    [System.SerializableAttribute()]
    public partial class LoadView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyHomeStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DispatchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DispatchPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HandleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFriendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ViewDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarrierRating {
            get {
                return this.CarrierRatingField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierRatingField, value) != true)) {
                    this.CarrierRatingField = value;
                    this.RaisePropertyChanged("CarrierRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyHomeState {
            get {
                return this.CompanyHomeStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyHomeStateField, value) != true)) {
                    this.CompanyHomeStateField = value;
                    this.RaisePropertyChanged("CompanyHomeState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DispatchName {
            get {
                return this.DispatchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DispatchNameField, value) != true)) {
                    this.DispatchNameField = value;
                    this.RaisePropertyChanged("DispatchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DispatchPhone {
            get {
                return this.DispatchPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.DispatchPhoneField, value) != true)) {
                    this.DispatchPhoneField = value;
                    this.RaisePropertyChanged("DispatchPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Handle {
            get {
                return this.HandleField;
            }
            set {
                if ((object.ReferenceEquals(this.HandleField, value) != true)) {
                    this.HandleField = value;
                    this.RaisePropertyChanged("Handle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFriend {
            get {
                return this.IsFriendField;
            }
            set {
                if ((this.IsFriendField.Equals(value) != true)) {
                    this.IsFriendField = value;
                    this.RaisePropertyChanged("IsFriend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ViewDate {
            get {
                return this.ViewDateField;
            }
            set {
                if ((this.ViewDateField.Equals(value) != true)) {
                    this.ViewDateField = value;
                    this.RaisePropertyChanged("ViewDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.truckstop.com/v11", ConfigurationName="TruckStopServiceReference.ILoadPosting")]
    public interface ILoadPosting {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/PostLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/PostLoadsResponse")]
        TruckStopService.TruckStopServiceReference.LoadPostingReturn PostLoads(TruckStopService.TruckStopServiceReference.LoadPostingRequest loads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/PostLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/PostLoadsResponse")]
        System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadPostingReturn> PostLoadsAsync(TruckStopService.TruckStopServiceReference.LoadPostingRequest loads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsResponse")]
        TruckStopService.TruckStopServiceReference.LoadPostingReturn DeleteLoads(TruckStopService.TruckStopServiceReference.LoadDeleteRequest loads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsResponse")]
        System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadPostingReturn> DeleteLoadsAsync(TruckStopService.TruckStopServiceReference.LoadDeleteRequest loads);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadsResponse")]
        TruckStopService.TruckStopServiceReference.LoadPostingListReturn GetLoads(TruckStopService.TruckStopServiceReference.LoadListRequest listRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoads", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadsResponse")]
        System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadPostingListReturn> GetLoadsAsync(TruckStopService.TruckStopServiceReference.LoadListRequest listRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsByLoadNumber", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsByLoadNumberResponse" +
            "")]
        TruckStopService.TruckStopServiceReference.LoadPostingReturn DeleteLoadsByLoadNumber(TruckStopService.TruckStopServiceReference.LoadDeleteByLoadNumberRequest deleteRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsByLoadNumber", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/DeleteLoadsByLoadNumberResponse" +
            "")]
        System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadPostingReturn> DeleteLoadsByLoadNumberAsync(TruckStopService.TruckStopServiceReference.LoadDeleteByLoadNumberRequest deleteRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViews", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsResponse")]
        TruckStopService.TruckStopServiceReference.LoadViewsReturn GetLoadViews(TruckStopService.TruckStopServiceReference.LoadViewsRequest loadNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViews", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsResponse")]
        System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadViewsReturn> GetLoadViewsAsync(TruckStopService.TruckStopServiceReference.LoadViewsRequest loadNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsByLoadNumber", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsByLoadNumberRespons" +
            "e")]
        TruckStopService.TruckStopServiceReference.LoadViewsReturn GetLoadViewsByLoadNumber(TruckStopService.TruckStopServiceReference.LoadViewsByLoadNumberRequest loadNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsByLoadNumber", ReplyAction="http://webservices.truckstop.com/v11/ILoadPosting/GetLoadViewsByLoadNumberRespons" +
            "e")]
        System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadViewsReturn> GetLoadViewsByLoadNumberAsync(TruckStopService.TruckStopServiceReference.LoadViewsByLoadNumberRequest loadNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoadPostingChannel : TruckStopService.TruckStopServiceReference.ILoadPosting, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadPostingClient : System.ServiceModel.ClientBase<TruckStopService.TruckStopServiceReference.ILoadPosting>, TruckStopService.TruckStopServiceReference.ILoadPosting {
        
        public LoadPostingClient() {
        }
        
        public LoadPostingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoadPostingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadPostingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadPostingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TruckStopService.TruckStopServiceReference.LoadPostingReturn PostLoads(TruckStopService.TruckStopServiceReference.LoadPostingRequest loads) {
            return base.Channel.PostLoads(loads);
        }
        
        public System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadPostingReturn> PostLoadsAsync(TruckStopService.TruckStopServiceReference.LoadPostingRequest loads) {
            return base.Channel.PostLoadsAsync(loads);
        }
        
        public TruckStopService.TruckStopServiceReference.LoadPostingReturn DeleteLoads(TruckStopService.TruckStopServiceReference.LoadDeleteRequest loads) {
            return base.Channel.DeleteLoads(loads);
        }
        
        public System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadPostingReturn> DeleteLoadsAsync(TruckStopService.TruckStopServiceReference.LoadDeleteRequest loads) {
            return base.Channel.DeleteLoadsAsync(loads);
        }
        
        public TruckStopService.TruckStopServiceReference.LoadPostingListReturn GetLoads(TruckStopService.TruckStopServiceReference.LoadListRequest listRequest) {
            return base.Channel.GetLoads(listRequest);
        }
        
        public System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadPostingListReturn> GetLoadsAsync(TruckStopService.TruckStopServiceReference.LoadListRequest listRequest) {
            return base.Channel.GetLoadsAsync(listRequest);
        }
        
        public TruckStopService.TruckStopServiceReference.LoadPostingReturn DeleteLoadsByLoadNumber(TruckStopService.TruckStopServiceReference.LoadDeleteByLoadNumberRequest deleteRequest) {
            return base.Channel.DeleteLoadsByLoadNumber(deleteRequest);
        }
        
        public System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadPostingReturn> DeleteLoadsByLoadNumberAsync(TruckStopService.TruckStopServiceReference.LoadDeleteByLoadNumberRequest deleteRequest) {
            return base.Channel.DeleteLoadsByLoadNumberAsync(deleteRequest);
        }
        
        public TruckStopService.TruckStopServiceReference.LoadViewsReturn GetLoadViews(TruckStopService.TruckStopServiceReference.LoadViewsRequest loadNumber) {
            return base.Channel.GetLoadViews(loadNumber);
        }
        
        public System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadViewsReturn> GetLoadViewsAsync(TruckStopService.TruckStopServiceReference.LoadViewsRequest loadNumber) {
            return base.Channel.GetLoadViewsAsync(loadNumber);
        }
        
        public TruckStopService.TruckStopServiceReference.LoadViewsReturn GetLoadViewsByLoadNumber(TruckStopService.TruckStopServiceReference.LoadViewsByLoadNumberRequest loadNumber) {
            return base.Channel.GetLoadViewsByLoadNumber(loadNumber);
        }
        
        public System.Threading.Tasks.Task<TruckStopService.TruckStopServiceReference.LoadViewsReturn> GetLoadViewsByLoadNumberAsync(TruckStopService.TruckStopServiceReference.LoadViewsByLoadNumberRequest loadNumber) {
            return base.Channel.GetLoadViewsByLoadNumberAsync(loadNumber);
        }
    }
}
